Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job                       count    min threads    max threads
----------------------  -------  -------------  -------------
all                           1              1              1
prepare_files_and_dirs        3              1              1
run_PDBminer                  3              1              1
total                         7              1              1

Select jobs to execute...

[Mon Oct  3 10:26:40 2022]
rule prepare_files_and_dirs:
    input: /data/user/krde/PDBminer/program
    output: /data/user/krde/PDBminer/program/results/P22307/P22307_input.csv
    jobid: 2
    wildcards: path=/data/user/krde/PDBminer/program, uniprot_id=P22307
    resources: tmpdir=/tmp

[Mon Oct  3 10:26:41 2022]
Finished job 2.
1 of 7 steps (14%) done
Select jobs to execute...

[Mon Oct  3 10:26:41 2022]
rule prepare_files_and_dirs:
    input: /data/user/krde/PDBminer/program
    output: /data/user/krde/PDBminer/program/results/P0A7Y7/P0A7Y7_input.csv
    jobid: 6
    wildcards: path=/data/user/krde/PDBminer/program, uniprot_id=P0A7Y7
    resources: tmpdir=/tmp

[Mon Oct  3 10:26:42 2022]
Finished job 6.
2 of 7 steps (29%) done
Select jobs to execute...

[Mon Oct  3 10:26:42 2022]
rule run_PDBminer:
    input: /data/user/krde/PDBminer/program/results/P0A7Y7/P0A7Y7_input.csv
    output: /data/user/krde/PDBminer/program/results/P0A7Y7/P0A7Y7_done.txt
    jobid: 5
    wildcards: path=/data/user/krde/PDBminer/program, uniprot_id=P0A7Y7
    resources: tmpdir=/tmp

[Mon Oct  3 10:26:42 2022]
Error in rule run_PDBminer:
    jobid: 5
    output: /data/user/krde/PDBminer/program/results/P0A7Y7/P0A7Y7_done.txt

RuleException:
WorkflowError in line 57 of /data/user/krde/PDBminer/program/snakefile:
Failed to open source file /scripts/PDBminer_run.py
FileNotFoundError: [Errno 2] No such file or directory: '/scripts/PDBminer_run.py'
  File "/data/user/krde/PDBminer/program/snakefile", line 57, in __rule_run_PDBminer
  File "/home/krde/.conda/envs/PDBminer/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-10-03T102639.685501.snakemake.log
